# Generated by Django 4.2.30 on 2026-07-22 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_userprofile_default_code_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_code',
        ),
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_user_display', models.CharField(max_length=120)),
                ('found_user_instagram', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance', models.FloatField()),
                ('direction', models.CharField(default='غير متوفر', max_length=20)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('found_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_found_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_found', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل لقاء',
                'verbose_name_plural': 'سجل اللقاءات',
                'ordering': ['-found_at'],
            },
        ),
    ]
