# Generated by Django 5.2.13 on 2026-07-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
