# Generated by Django 5.2.13 on 2026-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Material Symbol Name', max_length=50)),
            ],
            options={
                'verbose_name': 'اهتمام',
                'verbose_name_plural': 'الاهتمامات',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests_list',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='api.interest'),
        ),
    ]
