# Generated by Django 5.2.13 on 2026-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_intent',
            field=models.CharField(choices=[('NONE', 'متاح فقط'), ('CHAT', 'مستعد للدردشة'), ('COFFEE', 'أبحث عن شريك قهوة'), ('TECH', 'نقاش تقني'), ('HIRE', 'فرصة عمل / تعاون')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discovery_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visibility_level',
            field=models.CharField(choices=[('ALL', 'الجميع'), ('GENDER', 'نفس جنسي فقط'), ('GHOST', 'وضع التخفي (Ghost)')], default='ALL', max_length=10),
        ),
    ]
